from math import log
from .fixed_prec import FixedPrec

# base constants
NOMINAL_NANOSECS_PER_MICROSEC = 1_000
NOMINAL_MICROSECS_PER_SEC = 1_000_000
NOMINAL_SECS_PER_MIN = 60
NOMINAL_MINS_PER_HOUR = 60
NOMINAL_HOURS_PER_DAY = 24

# derived constants
NOMINAL_MICROSECS_PER_SEC_LOG_FIXEDPREC_RADIX = round(log(NOMINAL_MICROSECS_PER_SEC) / log(FixedPrec.RADIX))
NOMINAL_NANOSECS_PER_SEC = NOMINAL_NANOSECS_PER_MICROSEC * NOMINAL_MICROSECS_PER_SEC
NOMINAL_NANOSECS_PER_SEC_LOG_FIXEDPREC_RADIX = round(log(NOMINAL_NANOSECS_PER_SEC) / log(FixedPrec.RADIX))
NOMINAL_SECS_PER_HOUR = NOMINAL_MINS_PER_HOUR * NOMINAL_SECS_PER_MIN
NOMINAL_SECS_PER_DAY = NOMINAL_HOURS_PER_DAY * NOMINAL_SECS_PER_HOUR
NOMINAL_MICROSECS_PER_DAY = NOMINAL_SECS_PER_DAY * NOMINAL_MICROSECS_PER_SEC
NOMINAL_MINS_PER_DAY = NOMINAL_HOURS_PER_DAY * NOMINAL_MINS_PER_HOUR
