from math import log
from .fixed_prec import FixedPrec

# base constants
NOMINAL_NANOSECS_PER_MICROSEC = 1_000
NOMINAL_MICROSECS_PER_MILLISEC = 1_000
NOMINAL_MILLISECS_PER_SEC = 1_000
NOMINAL_SECS_PER_MIN = 60
NOMINAL_MINS_PER_HOUR = 60
NOMINAL_HOURS_PER_DAY = 24
NOMINAL_DAYS_PER_WEEK = 7
APPROX_DAYS_IN_YEAR = 365.2425
APPROX_MONTHS_IN_YEAR = 12

# derived constants
APPROX_DAYS_IN_MONTH = APPROX_DAYS_IN_YEAR / APPROX_MONTHS_IN_YEAR
NOMINAL_MICROSECS_PER_SEC = NOMINAL_MICROSECS_PER_MILLISEC * NOMINAL_MILLISECS_PER_SEC
NOMINAL_NANOSECS_PER_SEC = NOMINAL_NANOSECS_PER_MICROSEC * NOMINAL_MICROSECS_PER_SEC
NOMINAL_NANOSECS_PER_SEC_LOG_FIXEDPREC_RADIX = round(log(NOMINAL_NANOSECS_PER_SEC) / log(FixedPrec.RADIX))
NOMINAL_MICROSECS_PER_SEC_LOG_FIXEDPREC_RADIX = round(log(NOMINAL_MICROSECS_PER_SEC) / log(FixedPrec.RADIX))
NOMINAL_SECS_PER_HOUR = NOMINAL_MINS_PER_HOUR * NOMINAL_SECS_PER_MIN
NOMINAL_SECS_PER_DAY = NOMINAL_HOURS_PER_DAY * NOMINAL_SECS_PER_HOUR
NOMINAL_SECS_PER_WEEK = NOMINAL_DAYS_PER_WEEK * NOMINAL_SECS_PER_DAY
APPROX_SECS_PER_MONTH = APPROX_DAYS_IN_MONTH * NOMINAL_SECS_PER_DAY
APPROX_SECS_PER_YEAR = APPROX_DAYS_IN_YEAR * NOMINAL_SECS_PER_DAY
NOMINAL_MICROSECS_PER_DAY = NOMINAL_SECS_PER_DAY * NOMINAL_MICROSECS_PER_SEC
NOMINAL_MINS_PER_DAY = NOMINAL_HOURS_PER_DAY * NOMINAL_MINS_PER_HOUR
